apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: cnpe-storage-control-plane
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2026-06-10T07:09:21Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: database
  name: data-database-0
  namespace: storage-lab
  resourceVersion: "880"
  uid: 3d08db21-e2ca-42d5-9106-b6c301f5f4e1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cnpe-manual
  volumeMode: Filesystem
status:
  phase: Pending
